### ISSUE TITLE
Swagger issue

### ISSUE THREAD

**Issue by gatortarheel** [RedBirdOBX/City-Info-API-Demo#29]
Can you default the swagger documentation with the most current version number?

**Comment by RedBirdOBX** [comment]
The "version" shown in the release log / ReadMe isn't related to the API versions.  Right or wrong.  The Swagger version drop down will expose those resources tagged with API Version 2 - it cares not about my minor trivial versions of 1.x. Those are pretty much arbitrary and made up by me...to keep track of the releases.

I haven't yet built in the sophistication of having the app, when built in Release Mode, to automatically update a version number. 

And on a related note, if given a choice, I'd exclude using Swagger again.  It's easy to start up and start using but it's tough when doing it right, adding in versioning permissions, all possible response types, method annotation,  and all that.  I have yet to be in a real scenario where anyone actually truly uses it. Postman and a good ReadMe works just fine for me and I'm usually the only one using it.
